version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sulpharma
      - MYSQL_USER=sulpharma
      - MYSQL_PASSWORD=password